# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

FROM public.ecr.aws/bitnami/node:16.3.0-prod

WORKDIR /app

ARG ENV
ARG DEVICE_ID
ARG MQTT_BROKER_ADDRESS
ARG MQTT_KEY_FILE
ARG MQTT_CERT_FILE
ARG MQTT_CA_FILE
ARG MQTT_CLIENT_ID
ARG MOSQUITTO_URI
ARG MQTT_PROTOCOL
ARG USE_PROXY
ARG PROXY_HOST
ARG PROXY_PORT
ARG PROXY_USER
ARG PROXY_PASS


ENV ENV=$ENV
ENV DEVICE_ID=$DEVICE_ID
ENV MQTT_BROKER_ADDRESS=$MQTT_BROKER_ADDRESS
ENV MQTT_KEY_FILE=$MQTT_KEY_FILE
ENV MQTT_CERT_FILE=$MQTT_CERT_FILE
ENV MQTT_CA_FILE=$MQTT_CA_FILE
ENV MQTT_CLIENT_ID=$MQTT_CLIENT_ID
ENV MOSQUITTO_URI=$MOSQUITTO_URI
ENV USE_PROXY=$USE_PROXY
ENV PROXY_HOST=$PROXY_HOST
ENV PROXY_PORT=$PROXY_PORT
ENV PROXY_USER=$PROXY_USER
ENV PROXY_PASS=$PROXY_PASS

COPY package*.json ./
RUN npm install -g @babel/core @babel/cli @babel/preset-env babel-plugin-dynamic-import-node
RUN npm install --only=prod
COPY certs certs
COPY src src
COPY .babelrc.json .babelrc.json

CMD npm run start-local