# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: "3.8"
networks:
  main:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "mosquitto-net"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.10
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
    networks:
      - main

  aws-iot-core-to-mosquitto:
    build: .
    environment:
      - ENV=dev
      - DEVICE_ID=00123
      - MQTT_BROKER_ADDRESS={AWS_IOT_ENDPOINT}
      - MQTT_KEY_FILE={AWS_IOT_THING_PRIVATE_KEY_FILE ending with .pem.key}
      - MQTT_CERT_FILE={AWS_IOT_THING_CERTIFICATE_FILE ending with .pem.crt}
      - MQTT_CA_FILE={AWS_ROOT_CERTIFICATE .pem.crt}
      - MQTT_CLIENT_ID=aws_iot_core_to_mqtt_device
      - MOSQUITTO_URI=tcp://mosquitto:1883
      - MQTT_PROTOCOL=mtls
      - USE_PROXY=false
      - PROXY_HOST=localhost
      - PROXY_PORT=8888
      - PROXY_USER=
      - PROXY_PASS=
    networks:
      - main
